version: 2

jobs:
  install:
    branches:
      only:
        - master
    docker:
      - image: node:9.4.0
    steps:
      - checkout
      - run: yarn install
  test:
    branches:
      only:
        - master
    docker:
      - image: node:9.4.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - test:
          requires:
            - install
